/******************************************************************************
* Copyright (C) 2023-2025 Advanced Micro Devices, Inc. All rights reserved.
* SPDX-License-Identifier: MIT
******************************************************************************/


/*****************************************************************************/
/**
* @file xaie_lite_regdef_aie4.h
* @{
*
* This header file defines register offsets for lightweight version for AIE4
* APIs.
*
* <pre>
* MODIFICATION HISTORY:
*
* Ver   Who     Date     Changes
* ----- ------  -------- -----------------------------------------------------
* 1.0   Ramakant  27/12/2023  Initial creation
* </pre>
*
******************************************************************************/

#ifndef XAIE_LITE_REGDEF_AIE4_H_
#define XAIE_LITE_REGDEF_AIE4_H_

/***************************** Include Files *********************************/
#include "xaie4gbl_params.h"

/************************** Constant Definitions *****************************/
#define XAIE_EVENT_MASK					0x7F

// Single Mode app or Dual mode app A specific macros
#define XAIE_NOC_MOD_INTR_L2_ENABLE                     XAIE4GBL_NOC_MODULE_INTERRUPT_CONTROLLER_ENABLE_A
#define XAIE_NOC_MOD_INTR_L2_DISABLE                    XAIE4GBL_NOC_MODULE_INTERRUPT_CONTROLLER_DISABLE_A
#define XAIE_NOC_MOD_INTR_L2_MASK                       XAIE4GBL_NOC_MODULE_INTERRUPT_CONTROLLER_MASK_A
#define XAIE_NOC_MOD_INTR_L2_STATUS                     XAIE4GBL_NOC_MODULE_INTERRUPT_CONTROLLER_STATUS_A

// Dual mode app B specific macros
#define XAIE_NOC_MOD_INTR_L2_APP_B_ENABLE               XAIE4GBL_NOC_MODULE_INTERRUPT_CONTROLLER_ENABLE_B
#define XAIE_NOC_MOD_INTR_L2_APP_B_DISABLE              XAIE4GBL_NOC_MODULE_INTERRUPT_CONTROLLER_DISABLE_B
#define XAIE_NOC_MOD_INTR_L2_APP_B_MASK                 XAIE4GBL_NOC_MODULE_INTERRUPT_CONTROLLER_MASK_B
#define XAIE_NOC_MOD_INTR_L2_APP_B_STATUS               XAIE4GBL_NOC_MODULE_INTERRUPT_CONTROLLER_STATUS_B

// Common macros for both APP A & APP B
#define XAIE_NOC_MOD_INTR_L2_IRQ                        XAIE4GBL_NOC_MODULE_INTERRUPT_CONTROLLER_INTERRUPT_LINE_PRIVILEGED
#define XAIE_NOC_MOD_INTR_L2_IRQ_LSB                    XAIE4GBL_NOC_MODULE_INTERRUPT_CONTROLLER_INTERRUPT_LINE_NOC_INTERRUPT_APP_A_LSB_PRIVILEGED
#define XAIE_NOC_MOD_INTR_L2_IRQ_MASK                   XAIE4GBL_NOC_MODULE_INTERRUPT_CONTROLLER_INTERRUPT_LINE_NOC_INTERRUPT_APP_A_MASK_PRIVILEGED
#define XAIE_NOC_MOD_INTR_L2_APP_B_IRQ_LSB              XAIE4GBL_NOC_MODULE_INTERRUPT_CONTROLLER_INTERRUPT_LINE_NOC_INTERRUPT_APP_B_LSB_PRIVILEGED
#define XAIE_NOC_MOD_INTR_L2_APP_B_IRQ_MASK             XAIE4GBL_NOC_MODULE_INTERRUPT_CONTROLLER_INTERRUPT_LINE_NOC_INTERRUPT_APP_B_MASK_PRIVILEGED

#define XAIE_NOC_MOD_INTR_L2_GLOBAL_ENABLE              XAIE4GBL_NOC_MODULE_INTERRUPT_CONTROLLER_GLOBAL_ENABLE_PRIVILEGED
#define XAIE_NOC_MOD_INTR_L2_APP_A_GE_LSB               XAIE4GBL_NOC_MODULE_INTERRUPT_CONTROLLER_GLOBAL_ENABLE_ENABLE_APP_A_LSB_PRIVILEGED
#define XAIE_NOC_MOD_INTR_L2_APP_A_GE_MASK              XAIE4GBL_NOC_MODULE_INTERRUPT_CONTROLLER_GLOBAL_ENABLE_ENABLE_APP_A_MASK_PRIVILEGED
#define XAIE_NOC_MOD_INTR_L2_APP_B_GE_LSB               XAIE4GBL_NOC_MODULE_INTERRUPT_CONTROLLER_GLOBAL_ENABLE_ENABLE_APP_B_LSB_PRIVILEGED
#define XAIE_NOC_MOD_INTR_L2_APP_B_GE_MASK              XAIE4GBL_NOC_MODULE_INTERRUPT_CONTROLLER_GLOBAL_ENABLE_ENABLE_APP_B_MASK_PRIVILEGED

/**
 * HW Error Interrupt Handler specific definitions
 */
#define XAIE_PL_MOD_INTR_CNTRL_HW_ERR_ENABLE_A          XAIE4GBL_PL_MODULE_INTERRUPT_CONTROLLER_HW_ERROR_MASK_A_PRIVILEGED
#define XAIE_PL_MOD_INTR_CNTRL_HW_ERR_STATUS_A          XAIE4GBL_PL_MODULE_INTERRUPT_CONTROLLER_HW_ERROR_STATUS_A_PRIVILEGED
#define XAIE_PL_MOD_INTR_CNTRL_HW_ERR_IRQ_A             XAIE4GBL_PL_MODULE_INTERRUPT_CONTROLLER_HW_ERROR_INTERRUPT_A_PRIVILEGED
#define XAIE_PL_MOD_INTR_CNTRL_HW_ERR_ENABLE_B          XAIE4GBL_PL_MODULE_INTERRUPT_CONTROLLER_HW_ERROR_MASK_B_PRIVILEGED
#define XAIE_PL_MOD_INTR_CNTRL_HW_ERR_STATUS_B          XAIE4GBL_PL_MODULE_INTERRUPT_CONTROLLER_HW_ERROR_STATUS_B_PRIVILEGED
#define XAIE_PL_MOD_INTR_CNTRL_HW_ERR_IRQ_B             XAIE4GBL_PL_MODULE_INTERRUPT_CONTROLLER_HW_ERROR_INTERRUPT_B_PRIVILEGED
#define XAIE_PL_MOD_INTR_CNTRL_HW_ERR_CFG_LSB           XAIE4GBL_PL_MODULE_INTERRUPT_CONTROLLER_HW_ERROR_MASK_A_HW_UNCORRECTABLE_ERRORS_LSB_PRIVILEGED
#define XAIE_PL_MOD_INTR_CNTRL_HW_ERR_CFG_MASK          (XAIE4GBL_PL_MODULE_INTERRUPT_CONTROLLER_HW_ERROR_MASK_A_HW_UNCORRECTABLE_ERRORS_MASK_PRIVILEGED || \
                                                        XAIE4GBL_PL_MODULE_INTERRUPT_CONTROLLER_HW_ERROR_MASK_A_HW_CORRECTABLE_ERRORS_MASK_PRIVILEGED   || \
                                                        XAIE4GBL_PL_MODULE_INTERRUPT_CONTROLLER_HW_ERROR_MASK_A_AXI_ERRORS_MASK_PRIVILEGED)

/**
 * SHIM Tile Event Broadcast Macros
 */
#define XAIE_PL_MOD_EVENT_GENERATE_A_0      XAIE4GBL_PL_MODULE_EVENT_GENERATE_A
#define XAIE_PL_MOD_EVENT_GENERATE_B_0      (XAIE4GBL_PL_MODULE_EVENT_GENERATE_A | XAIE4_MASK_VALUE_APP_B)
#define XAIE_PL_MOD_EVENT_BROADCAST_A_0                 XAIE4GBL_PL_MODULE_EVENT_BROADCAST_A_0
#define XAIE_PL_MOD_EVENT_BROADCAST_B_0                 (XAIE4GBL_PL_MODULE_EVENT_BROADCAST_A_0 | XAIE4_MASK_VALUE_APP_B)
#define XAIE_PL_MOD_EVENT_BROADCAST_A_BLOCK_SOUTH_SET   XAIE4GBL_PL_MODULE_EVENT_BROADCAST_A_BLOCK_SOUTH_SET
#define XAIE_PL_MOD_EVENT_BROADCAST_A_BLOCK_WEST_SET    XAIE4GBL_PL_MODULE_EVENT_BROADCAST_A_BLOCK_WEST_SET
#define XAIE_PL_MOD_EVENT_BROADCAST_A_BLOCK_NORTH_SET   XAIE4GBL_PL_MODULE_EVENT_BROADCAST_A_BLOCK_NORTH_SET
#define XAIE_PL_MOD_EVENT_BROADCAST_A_BLOCK_EAST_SET    XAIE4GBL_PL_MODULE_EVENT_BROADCAST_A_BLOCK_EAST_SET

// App B Event Broadcast does not have east & west block config registers
#define XAIE_PL_MOD_EVENT_BROADCAST_B_BLOCK_SOUTH_SET   (XAIE4GBL_PL_MODULE_EVENT_BROADCAST_A_BLOCK_SOUTH_SET | XAIE4_MASK_VALUE_APP_B)
#define XAIE_PL_MOD_EVENT_BROADCAST_B_BLOCK_NORTH_SET   (XAIE4GBL_PL_MODULE_EVENT_BROADCAST_A_BLOCK_NORTH_SET | XAIE4_MASK_VALUE_APP_B)

/**
 * MEM Tile Event Broadcast Macros
 */
#define XAIE_MEM_TILE_EVENT_BROADCAST_A_0               XAIE4GBL_MEM_TILE_MODULE_EVENT_BROADCAST_A_0
#define XAIE_MEM_TILE_EVENT_BROADCAST_B_0               (XAIE4GBL_MEM_TILE_MODULE_EVENT_BROADCAST_A_0 | XAIE4_MASK_VALUE_APP_B)
#define XAIE_MEM_TILE_EVENT_BROADCAST_A_BLOCK_SOUTH_SET XAIE4GBL_MEM_TILE_MODULE_EVENT_BROADCAST_A_BLOCK_SOUTH_SET
#define XAIE_MEM_TILE_EVENT_BROADCAST_A_BLOCK_WEST_SET  XAIE4GBL_MEM_TILE_MODULE_EVENT_BROADCAST_A_BLOCK_WEST_SET
#define XAIE_MEM_TILE_EVENT_BROADCAST_A_BLOCK_NORTH_SET XAIE4GBL_MEM_TILE_MODULE_EVENT_BROADCAST_A_BLOCK_NORTH_SET
#define XAIE_MEM_TILE_EVENT_BROADCAST_A_BLOCK_EAST_SET  XAIE4GBL_MEM_TILE_MODULE_EVENT_BROADCAST_A_BLOCK_EAST_SET

// App B Event Broadcast does not have east & west block config registers
#define XAIE_MEM_TILE_EVENT_BROADCAST_B_BLOCK_SOUTH_SET (XAIE4GBL_MEM_TILE_MODULE_EVENT_BROADCAST_A_BLOCK_SOUTH_SET | XAIE4_MASK_VALUE_APP_B)
#define XAIE_MEM_TILE_EVENT_BROADCAST_B_BLOCK_NORTH_SET (XAIE4GBL_MEM_TILE_MODULE_EVENT_BROADCAST_A_BLOCK_NORTH_SET | XAIE4_MASK_VALUE_APP_B)

/**
 * CORE Tile Event Broadcast Macros
 */
#define XAIE_AIE_TILE_EVENT_BROADCAST_0                 XAIE4GBL_CORE_MODULE_EVENT_BROADCAST0
#define XAIE_AIE_TILE_EVENT_BROADCAST_BLOCK_SOUTH_SET   XAIE4GBL_CORE_MODULE_EVENT_BROADCAST_BLOCK_SOUTH_SET
#define XAIE_AIE_TILE_EVENT_BROADCAST_BLOCK_WEST_SET    XAIE4GBL_CORE_MODULE_EVENT_BROADCAST_BLOCK_WEST_SET
#define XAIE_AIE_TILE_EVENT_BROADCAST_BLOCK_NORTH_SET   XAIE4GBL_CORE_MODULE_EVENT_BROADCAST_BLOCK_NORTH_SET
#define XAIE_AIE_TILE_EVENT_BROADCAST_BLOCK_EAST_SET    XAIE4GBL_CORE_MODULE_EVENT_BROADCAST_BLOCK_EAST_SET

/**
 * Registers definitions added to resolve build error due to interrupt backtrack
 * Need to change when Interrupt Backtrack is modified
 */
#define XAIE_MEM_TILE_EVENT_GROUP_ERROR0                163     // First Event Number of Mem Tile Group Error 0
#define XAIE_MEM_TILE_EVENT_BROADCAST0                  177     // Event Number of Mem Tile Broadcast Channel 0
#define XAIE_MEM_TILE_BASE_EVENT_STATUS                 XAIE4GBL_MEM_TILE_MODULE_EVENT_STATUS_A_0
#define XAIE_MEM_TILE_BASE_EVENT_STATUS_B               (XAIE4GBL_MEM_TILE_MODULE_EVENT_STATUS_A_0 | XAIE4_MASK_VALUE_APP_B)
#define XAIE_MEM_TILE_GROUP_ERROR0_ENABLE               XAIE4GBL_MEM_TILE_MODULE_EVENT_GROUP_ERROR_ENABLE_A
#define XAIE_MEM_TILE_GROUP_ERROR0_ENABLE_B             (XAIE4GBL_MEM_TILE_MODULE_EVENT_GROUP_ERROR_ENABLE_A | XAIE4_MASK_VALUE_APP_B)
#define XAIE_MEM_TILE_BASE_EVENT_BROADCAST              XAIE4GBL_MEM_TILE_MODULE_EVENT_BROADCAST_A_0
#define XAIE_MEM_TILE_BASE_EVENT_BROADCAST_B            (XAIE4GBL_MEM_TILE_MODULE_EVENT_BROADCAST_A_0 | XAIE4_MASK_VALUE_APP_B)

#define XAIE_PL_MOD_EVENT_GROUP_ERROR0                  153     // First Event Number of Shim Tile Group Error 0
#define XAIE_PL_MOD_EVENT_BROADCAST0                    232     // Event Number of Shim Tile Broadcast Channel 0
#define XAIE_PL_MOD_BASE_EVENT_STATUS                   XAIE4GBL_PL_MODULE_EVENT_STATUS_A_0
#define XAIE_PL_MOD_BASE_EVENT_STATUS_B                 (XAIE4GBL_PL_MODULE_EVENT_STATUS_A_0 | XAIE4_MASK_VALUE_APP_B)
#define XAIE_PL_MOD_GROUP_ERROR0_ENABLE                 XAIE4GBL_PL_MODULE_EVENT_GROUP_ERRORS_ENABLE_A
#define XAIE_PL_MOD_GROUP_ERROR0_ENABLE_B               (XAIE4GBL_PL_MODULE_EVENT_GROUP_ERRORS_ENABLE_A | XAIE4_MASK_VALUE_APP_B)
#define XAIE_SHIM_TILE_BASE_EVENT_BROADCAST             XAIE4GBL_PL_MODULE_EVENT_BROADCAST_A_0
#define XAIE_SHIM_TILE_BASE_EVENT_BROADCAST_B           (XAIE4GBL_PL_MODULE_EVENT_BROADCAST_A_0 | XAIE4_MASK_VALUE_APP_B)

#define XAIE_CORE_MOD_EVENT_GROUP_ERROR0                89      // First Event Number of Core Tile Group Error 0
#define XAIE_CORE_MOD_EVENT_BROADCAST0                  218     // Event Number of Core Tile Broadcast Channel 0
#define XAIE_CORE_MOD_BASE_EVENT_STATUS                 XAIE4GBL_CORE_MODULE_EVENT_STATUS0
#define XAIE_CORE_MOD_BASE_EVENT_BROADCAST              XAIE4GBL_CORE_MODULE_EVENT_BROADCAST0
#define XAIE_CORE_MOD_GROUP_ERROR0_ENABLE               XAIE4GBL_CORE_MODULE_EVENT_GROUP_ERRORS0_ENABLE
#define XAIE_CORE_MOD_BASE_EVENT_BROADCAST              XAIE4GBL_CORE_MODULE_EVENT_BROADCAST0

/* Added empty definitions to resolve build error */
#define XAIE_PL_MOD_COL_RST_LSB                         0
#define XAIE_PL_MOD_COL_RST_MASK                        0

#define XAIE_PL_MOD_DUAL_APP_MODE                       XAIE4GBL_PL_MODULE_DUAL_APP_MODE_PRIVILEGED
#define XAIE_PL_MOD_DUAL_APP_MODE_LSB                   XAIE4GBL_PL_MODULE_DUAL_APP_MODE_DUAL_APP_MODE_LSB_PRIVILEGED
#define XAIE_PL_MOD_DUAL_APP_MODE_MASK                  XAIE4GBL_PL_MODULE_DUAL_APP_MODE_DUAL_APP_MODE_MASK_PRIVILEGED

#define XAIE_PL_MOD_COL_RST_REGOFF                      XAIE4GBL_PL_MODULE_APPLICATION_RESET_CONTROL_HW_CLK_STOP_PRIVILEGED
#define XAIE_PL_MOD_COL_RST_APP_A_LSB                   XAIE4GBL_PL_MODULE_APPLICATION_RESET_CONTROL_HW_CLK_STOP_APP_A_RESET_LSB_PRIVILEGED
#define XAIE_PL_MOD_COL_RST_APP_A_MASK                  XAIE4GBL_PL_MODULE_APPLICATION_RESET_CONTROL_HW_CLK_STOP_APP_A_RESET_MASK_PRIVILEGED
#define XAIE_PL_MOD_COL_RST_APP_B_LSB                   XAIE4GBL_PL_MODULE_APPLICATION_RESET_CONTROL_HW_CLK_STOP_APP_B_RESET_LSB_PRIVILEGED
#define XAIE_PL_MOD_COL_RST_APP_B_MASK                  XAIE4GBL_PL_MODULE_APPLICATION_RESET_CONTROL_HW_CLK_STOP_APP_B_RESET_MASK_PRIVILEGED

/* DMA Pause Registers */
#define XAIE_PL_MOD_DMA_PAUSE_REGOFF                    XAIE4GBL_NOC_MODULE_DMA_PAUSE_PRIVILEGED
#define XAIE_PL_MOD_DMA_PAUSE_MASK                      XAIE4GBL_NOC_MODULE_DMA_PAUSE_MASK_PRIVILEGED
#define XAIE_PL_MOD_DMA_PAUSE_LSB                       XAIE4GBL_NOC_MODULE_DMA_PAUSE_S2MM_0_LSB_PRIVILEGED

#define XAIE_PL_MOD_DMA_PAUSE_APP_A_MASK                XAIE4GBL_NOC_MODULE_DMA_PAUSE_TRACE_S2MM_MASK_PRIVILEGED | XAIE4GBL_NOC_MODULE_DMA_PAUSE_S2MM_0_MASK_PRIVILEGED | XAIE4GBL_NOC_MODULE_DMA_PAUSE_MM2S_0_MASK_PRIVILEGED | XAIE4GBL_NOC_MODULE_DMA_PAUSE_MM2S_1_MASK_PRIVILEGED | XAIE4GBL_NOC_MODULE_DMA_PAUSE_CONTROL_MM2S_0_MASK_PRIVILEGED
#define XAIE_PL_MOD_DMA_PAUSE_APP_B_MASK                XAIE4GBL_NOC_MODULE_DMA_PAUSE_TRACE_S2MM_MASK_PRIVILEGED | XAIE4GBL_NOC_MODULE_DMA_PAUSE_S2MM_1_MASK_PRIVILEGED | XAIE4GBL_NOC_MODULE_DMA_PAUSE_MM2S_2_MASK_PRIVILEGED | XAIE4GBL_NOC_MODULE_DMA_PAUSE_MM2S_3_MASK_PRIVILEGED | XAIE4GBL_NOC_MODULE_DMA_PAUSE_CONTROL_MM2S_1_MASK_PRIVILEGED

#define XAIE_PL_MOD_UC_DMA_A_PAUSE_REGOFF               XAIE4GBL_PL_MODULE_UC_DMA_PAUSE_A_PRIVILEGED
#define XAIE_PL_MOD_UC_DMA_A_PAUSE_LSB                  XAIE4GBL_PL_MODULE_UC_DMA_PAUSE_A_DM2MM_LSB_PRIVILEGED
#define XAIE_PL_MOD_UC_DMA_A_PAUSE_MASK                 XAIE4GBL_PL_MODULE_UC_DMA_PAUSE_A_MASK_PRIVILEGED

#define XAIE_PL_MOD_UC_DMA_B_PAUSE_REGOFF               XAIE4GBL_PL_MODULE_UC_DMA_PAUSE_B_PRIVILEGED
#define XAIE_PL_MOD_UC_DMA_B_PAUSE_LSB                  XAIE4GBL_PL_MODULE_UC_DMA_PAUSE_B_DM2MM_LSB_PRIVILEGED
#define XAIE_PL_MOD_UC_DMA_B_PAUSE_MASK                 XAIE4GBL_PL_MODULE_UC_DMA_PAUSE_B_MASK_PRIVILEGED

/* AXI-MM Outstanding Transactions Monitoring Register */
#define XAIE_NOC_MOD_AXI_MM_OUTSTANDING_TRANSACTIONS_REGOFF XAIE4GBL_NOC_MODULE_AXI_MM_OUTSTANDING_TRANSACTIONS_PRIVILEGED
#define XAIE_NOC_MOD_AXI_MM_OUTSTANDING_TRANSACTIONS_MASK   XAIE4GBL_NOC_MODULE_AXI_MM_OUTSTANDING_TRANSACTIONS_MASK_PRIVILEGED
#define XAIE_NOC_MOD_AXI_MM_OUTSTANDING_TRANSACTIONS_LSB    XAIE4GBL_NOC_MODULE_AXI_MM_OUTSTANDING_TRANSACTIONS_SHIM_DMA_TO_NMU_0_LSB_PRIVILEGED

/* Column Clock Control Registers */
#define XAIE_PL_MOD_COL_CLKCNTR_REGOFF                      XAIE4GBL_PL_MODULE_COLUMN_CLOCK_CONTROL_PRIVILEGED
#define XAIE_PL_MOD_COL_CLKCNTR_CLKBUF_ENABLE_MASK          XAIE4GBL_PL_MODULE_COLUMN_CLOCK_CONTROL_COLUMN_CLOCK_BUFFER_ENABLE_MASK_PRIVILEGED
#define XAIE_PL_MOD_COL_CLKCNTR_CLKBUF_ENABLE_LSB           XAIE4GBL_PL_MODULE_COLUMN_CLOCK_CONTROL_COLUMN_CLOCK_BUFFER_ENABLE_LSB_PRIVILEGED
#define XAIE_PL_MOD_COL_CLKCNTR_TILE_CLK_CLKBUF_ENABLE_LSB  XAIE4GBL_PL_MODULE_COLUMN_CLOCK_CONTROL_TILE_CLOCK_BUFFER_ENABLE_LSB_PRIVILEGED
#define XAIE_PL_MOD_COL_CLKCNTR_TILE_CLK_CLKBUF_ENABLE_MASK XAIE4GBL_PL_MODULE_COLUMN_CLOCK_CONTROL_TILE_CLOCK_BUFFER_ENABLE_MASK_PRIVILEGED

#define XAIE_PL_MOD_MEDIUM_GRAINED_CLOCK_GATING_CONTROL    XAIE4GBL_PL_MODULE_MEDIUM_GRAINED_CLOCK_GATING_CONTROL
#define XAIE_MEMTILE_MEDIUM_GRAINED_CLOCK_GATING_CONTROL   XAIE4GBL_MEM_TILE_MODULE_MEDIUM_GRAINED_CLOCK_GATING_CONTROL
#define XAIE_AIETILE_MEDIUM_GRAINED_CLOCK_GATING_CONTROL   XAIE4GBL_CORE_MODULE_MEDIUM_GRAINED_CLOCK_GATING_CONTROL

/* PL Module Module 0 Clock Control Registers */
#define XAIE4GBL_PL_MODULE_MODULE_CLOCK_CONTROL             XAIE4GBL_PL_MODULE_MODULE_CLOCK_CONTROL_0_PRIVILEGED
#define XAIE_PL_MOD_UCONTROLLER_CLOCK_ENABLE_MASK           XAIE4GBL_PL_MODULE_MODULE_CLOCK_CONTROL_0_UCONTROLLER_CLOCK_ENABLE_MASK_PRIVILEGED
#define XAIE_PL_MOD_UCONTROLLER_CLOCK_ENABLE_LSB            XAIE4GBL_PL_MODULE_MODULE_CLOCK_CONTROL_0_UCONTROLLER_CLOCK_ENABLE_LSB_PRIVILEGED

/* Compute Tile Module Clock Control Register */
#define XAIE_AIE_TILE_MODULE_CLOCKCTR_REGOFF                XAIE4GBL_CORE_MODULE_MODULE_CLOCK_CONTROL_PRIVILEGED
#define XAIE_AIE_TILE_MODULE_CLOCKCTR_MASK                  XAIE4GBL_CORE_MODULE_MODULE_CLOCK_CONTROL_CORE_MODULE_CLOCK_ENABLE_MASK_PRIVILEGED | XAIE4GBL_CORE_MODULE_MODULE_CLOCK_CONTROL_MEMORY_MODULE_CLOCK_ENABLE_MASK_PRIVILEGED
#define XAIE_AIE_TILE_MODULE_CLOCKCTR_CORE_MODULE_MASK      XAIE4GBL_CORE_MODULE_MODULE_CLOCK_CONTROL_CORE_MODULE_CLOCK_ENABLE_MASK_PRIVILEGED
#define XAIE_AIE_TILE_MODULE_CLOCKCTR_MEMORY_MODULE_MASK    XAIE4GBL_CORE_MODULE_MODULE_CLOCK_CONTROL_MEMORY_MODULE_CLOCK_ENABLE_MASK_PRIVILEGED
#define XAIE_AIE_TILE_MODULE_CLOCKCTR_CORE_MODULE_LSB       XAIE4GBL_CORE_MODULE_MODULE_CLOCK_CONTROL_CORE_MODULE_CLOCK_ENABLE_LSB_PRIVILEGED
#define XAIE_AIE_TILE_MODULE_CLOCKCTR_MEMORY_MODULE_LSB     XAIE4GBL_CORE_MODULE_MODULE_CLOCK_CONTROL_MEMORY_MODULE_CLOCK_ENABLE_LSB_PRIVILEGED

/* Shim Tile NOC module A SMID Register */
#define XAIE_PL_MOD_NOC_SMID_A_REGOFF                       XAIE4GBL_NOC_MODULE_SMID_A_PRIVILEGED
#define XAIE_PL_MOD_NOC_SMID_A_LSB                          XAIE4GBL_NOC_MODULE_SMID_A_SMID_LSB_PRIVILEGED
#define XAIE_PL_MOD_NOC_SMID_A_MASK                         XAIE4GBL_NOC_MODULE_SMID_A_MASK_PRIVILEGED

/* Shim Tile NOC module B SMID Register */
#define XAIE_PL_MOD_NOC_SMID_B_REGOFF                       XAIE4GBL_NOC_MODULE_SMID_B_PRIVILEGED
#define XAIE_PL_MOD_NOC_SMID_B_LSB                          XAIE4GBL_NOC_MODULE_SMID_B_SMID_LSB_PRIVILEGED
#define XAIE_PL_MOD_NOC_SMID_B_MASK                         XAIE4GBL_NOC_MODULE_SMID_B_MASK_PRIVILEGED

/* Shim Tile NOC Module AxUSER_A Register */
#define XAIE_PL_MOD_NOC_AxUSER_A_REGOFF                     XAIE4GBL_NOC_MODULE_AXUSER_A_PRIVILEGED
#define XAIE_PL_MOD_NOC_AxUSER_A_LSB                        XAIE4GBL_NOC_MODULE_AXUSER_A_AXUSER_LSB_PRIVILEGED
#define XAIE_PL_MOD_NOC_AxUSER_A_MASK                       XAIE4GBL_NOC_MODULE_AXUSER_A_MASK_PRIVILEGED

/* Shim Tile NOC Module AxUSER_B Register */
#define XAIE_PL_MOD_NOC_AxUSER_B_REGOFF                     XAIE4GBL_NOC_MODULE_AXUSER_B_PRIVILEGED
#define XAIE_PL_MOD_NOC_AxUSER_B_LSB                        XAIE4GBL_NOC_MODULE_AXUSER_B_AXUSER_LSB_PRIVILEGED
#define XAIE_PL_MOD_NOC_AxUSER_B_MASK                       XAIE4GBL_NOC_MODULE_AXUSER_B_MASK_PRIVILEGED

/* Shim Tile NOC Module Trusted_Keys A Register */
#define XAIE_PL_MOD_NOC_TRUSTED_KEYS_A_REGOFF               XAIE4GBL_NOC_MODULE_TRUSTED_KEYS_A_PRIVILEGED
#define XAIE_PL_MOD_NOC_TRUSTED_KEYS_A_LSB                  XAIE4GBL_NOC_MODULE_TRUSTED_KEYS_A_KEY1_LSB_PRIVILEGED
#define XAIE_PL_MOD_NOC_TRUSTED_KEYS_A_MASK                 XAIE4GBL_NOC_MODULE_TRUSTED_KEYS_A_MASK_PRIVILEGED

/* Shim Tile NOC Module Trusted_Keys B Register */
#define XAIE_PL_MOD_NOC_TRUSTED_KEYS_B_REGOFF               XAIE4GBL_NOC_MODULE_TRUSTED_KEYS_B_PRIVILEGED
#define XAIE_PL_MOD_NOC_TRUSTED_KEYS_B_LSB                  XAIE4GBL_NOC_MODULE_TRUSTED_KEYS_B_KEY1_LSB_PRIVILEGED
#define XAIE_PL_MOD_NOC_TRUSTED_KEYS_B_MASK                 XAIE4GBL_NOC_MODULE_TRUSTED_KEYS_B_MASK_PRIVILEGED

#define XAIE_PL_MOD_TILE_CNTR_REGOFF                        XAIE4GBL_PL_MODULE_TILE_CONTROL_PRIVILEGED
#define XAIE_PL_MOD_TILE_CNTR_ISOLATE_EAST_LSB              XAIE4GBL_PL_MODULE_TILE_CONTROL_ISOLATE_FROM_EAST_LSB_PRIVILEGED
#define XAIE_PL_MOD_TILE_CNTR_ISOLATE_EAST_MASK             XAIE4GBL_PL_MODULE_TILE_CONTROL_ISOLATE_FROM_EAST_MASK_PRIVILEGED
#define XAIE_PL_MOD_TILE_CNTR_ISOLATE_NORTH_LSB             XAIE4GBL_PL_MODULE_TILE_CONTROL_ISOLATE_FROM_NORTH_LSB_PRIVILEGED
#define XAIE_PL_MOD_TILE_CNTR_ISOLATE_NORTH_MASK            XAIE4GBL_PL_MODULE_TILE_CONTROL_ISOLATE_FROM_NORTH_MASK_PRIVILEGED
#define XAIE_PL_MOD_TILE_CNTR_ISOLATE_WEST_LSB              XAIE4GBL_PL_MODULE_TILE_CONTROL_ISOLATE_FROM_WEST_LSB_PRIVILEGED
#define XAIE_PL_MOD_TILE_CNTR_ISOLATE_WEST_MASK             XAIE4GBL_PL_MODULE_TILE_CONTROL_ISOLATE_FROM_WEST_MASK_PRIVILEGED
#define XAIE_PL_MOD_TILE_CNTR_ISOLATE_SOUTH_LSB             XAIE4GBL_PL_MODULE_TILE_CONTROL_ISOLATE_FROM_SOUTH_LSB_PRIVILEGED
#define XAIE_PL_MOD_TILE_CNTR_ISOLATE_SOUTH_MASK            XAIE4GBL_PL_MODULE_TILE_CONTROL_ISOLATE_FROM_SOUTH_MASK_PRIVILEGED

#define XAIE_PL_MOD_TILE_CNTR_AXIMM_REGOFF                  XAIE4GBL_PL_MODULE_TILE_CONTROL_AXI_MM_PRIVILEGED
#define XAIE_PL_MOD_TILE_CNTR_AXIMM_ISOLATE_EAST_LSB        XAIE4GBL_PL_MODULE_TILE_CONTROL_AXI_MM_ISOLATE_FROM_EAST_LSB_PRIVILEGED
#define XAIE_PL_MOD_TILE_CNTR_AXIMM_ISOLATE_EAST_MASK       XAIE4GBL_PL_MODULE_TILE_CONTROL_AXI_MM_ISOLATE_FROM_EAST_MASK_PRIVILEGED
#define XAIE_PL_MOD_TILE_CNTR_AXIMM_ISOLATE_WEST_LSB        XAIE4GBL_PL_MODULE_TILE_CONTROL_AXI_MM_ISOLATE_FROM_WEST_LSB_PRIVILEGED
#define XAIE_PL_MOD_TILE_CNTR_AXIMM_ISOLATE_WEST_MASK       XAIE4GBL_PL_MODULE_TILE_CONTROL_AXI_MM_ISOLATE_FROM_WEST_MASK_PRIVILEGED

#define XAIE_PL_MODULE_MEMORY_ZEROIZATION                   XAIE4GBL_PL_MODULE_MEMORY_ZEROIZATION_A_PRIVILEGED
#define XAIE_PL_MODULE_MEMORY_ZEROIZATION_MASK              XAIE4GBL_PL_MODULE_MEMORY_ZEROIZATION_A_MASK_PRIVILEGED
#define XAIE_PL_MODULE_MEMORY_A_DM_ZEROIZATION_MASK         XAIE4GBL_PL_MODULE_MEMORY_ZEROIZATION_A_DM_ZEROIZATION_MASK_PRIVILEGED
#define XAIE_PL_MODULE_MEMORY_A_DM_ZEROIZATION_LSB          XAIE4GBL_PL_MODULE_MEMORY_ZEROIZATION_A_DM_ZEROIZATION_LSB_PRIVILEGED
#define XAIE_PL_MODULE_MEMORY_A_PRIVATE_DM_ZEROIZATION_MASK XAIE4GBL_PL_MODULE_MEMORY_ZEROIZATION_A_PRIVATE_DM_ZEROIZATION_MASK_PRIVILEGED
#define XAIE_PL_MODULE_MEMORY_ZEROIZATION_B                 XAIE4GBL_PL_MODULE_MEMORY_ZEROIZATION_B_PRIVILEGED
#define XAIE_PL_MODULE_MEMORY_ZEROIZATION_B_MASK            XAIE4GBL_PL_MODULE_MEMORY_ZEROIZATION_B_MASK_PRIVILEGED
#define XAIE_PL_MODULE_MEMORY_B_PRIVATE_DM_ZEROIZATION_MASK XAIE4GBL_PL_MODULE_MEMORY_ZEROIZATION_B_PRIVATE_DM_ZEROIZATION_MASK_PRIVILEGED
#define XAIE_PL_MODULE_MEMORY_B_DM_ZEROIZATION_MASK         XAIE4GBL_PL_MODULE_MEMORY_ZEROIZATION_B_DM_ZEROIZATION_MASK_PRIVILEGED
#define XAIE_PL_MODULE_MEMORY_B_DM_ZEROIZATION_LSB          XAIE4GBL_PL_MODULE_MEMORY_ZEROIZATION_B_DM_ZEROIZATION_LSB_PRIVILEGED
#define XAIE_PL_MODULE_MEMORY_PM_ZEROIZATION_MASK           XAIE4GBL_PL_MODULE_MEMORY_ZEROIZATION_A_PM_ZEROIZATION_MASK_PRIVILEGED
#define XAIE_PL_MODULE_MEMORY_PM_ZEROIZATION_LSB            XAIE4GBL_PL_MODULE_MEMORY_ZEROIZATION_A_PM_ZEROIZATION_LSB_PRIVILEGED

#define XAIE_PL_MODULE_MEMORY_A_ALL_DM_ZEROIZATION_MASK     XAIE4GBL_PL_MODULE_MEMORY_ZEROIZATION_A_DM_ZEROIZATION_MASK_PRIVILEGED | XAIE4GBL_PL_MODULE_MEMORY_ZEROIZATION_A_PRIVATE_DM_ZEROIZATION_MASK_PRIVILEGED
#define XAIE_PL_MODULE_MEMORY_B_ALL_DM_ZEROIZATION_MASK     XAIE4GBL_PL_MODULE_MEMORY_ZEROIZATION_B_DM_ZEROIZATION_MASK_PRIVILEGED | XAIE4GBL_PL_MODULE_MEMORY_ZEROIZATION_B_PRIVATE_DM_ZEROIZATION_MASK_PRIVILEGED

#define XAIE_NOC_AXIMM_CONF_REGOFF                          XAIE4GBL_NOC_MODULE_ME_AXIMM_CONFIG_PRIVILEGED
#define XAIE_NOC_AXIMM_CONF_SLVERR_BLOCK_LSB                XAIE4GBL_NOC_MODULE_ME_AXIMM_CONFIG_SLVERR_BLOCK_LSB_PRIVILEGED
#define XAIE_NOC_AXIMM_CONF_SLVERR_BLOCK_MASK               XAIE4GBL_NOC_MODULE_ME_AXIMM_CONFIG_SLVERR_BLOCK_MASK_PRIVILEGED
#define XAIE_NOC_AXIMM_CONF_DECERR_BLOCK_LSB                XAIE4GBL_NOC_MODULE_ME_AXIMM_CONFIG_DECERR_BLOCK_LSB_PRIVILEGED
#define XAIE_NOC_AXIMM_CONF_DECERR_BLOCK_MASK               XAIE4GBL_NOC_MODULE_ME_AXIMM_CONFIG_DECERR_BLOCK_MASK_PRIVILEGED

#define XAIE_CORE_MOD_DUAL_APP_MODE                         XAIE4GBL_CORE_MODULE_DUAL_APP_MODE_PRIVILEGED
#define XAIE_CORE_MOD_DUAL_APP_MODE_LSB                     XAIE4GBL_CORE_MODULE_DUAL_APP_MODE_DUAL_APP_MODE_LSB_PRIVILEGED
#define XAIE_CORE_MOD_DUAL_APP_MODE_MASK                    XAIE4GBL_CORE_MODULE_DUAL_APP_MODE_DUAL_APP_MODE_MASK_PRIVILEGED

#define XAIE_CORE_MOD_TILE_CNTR_REGOFF                      XAIE4GBL_CORE_MODULE_TILE_CONTROL_PRIVILEGED
#define XAIE_CORE_MOD_TILE_CNTR_ISOLATE_EAST_LSB            XAIE4GBL_CORE_MODULE_TILE_CONTROL_ISOLATE_FROM_EAST_LSB_PRIVILEGED
#define XAIE_CORE_MOD_TILE_CNTR_ISOLATE_EAST_MASK           XAIE4GBL_CORE_MODULE_TILE_CONTROL_ISOLATE_FROM_EAST_MASK_PRIVILEGED
#define XAIE_CORE_MOD_TILE_CNTR_ISOLATE_NORTH_LSB           XAIE4GBL_CORE_MODULE_TILE_CONTROL_ISOLATE_FROM_NORTH_LSB_PRIVILEGED
#define XAIE_CORE_MOD_TILE_CNTR_ISOLATE_NORTH_MASK          XAIE4GBL_CORE_MODULE_TILE_CONTROL_ISOLATE_FROM_NORTH_MASK_PRIVILEGED
#define XAIE_CORE_MOD_TILE_CNTR_ISOLATE_WEST_LSB            XAIE4GBL_CORE_MODULE_TILE_CONTROL_ISOLATE_FROM_WEST_LSB_PRIVILEGED
#define XAIE_CORE_MOD_TILE_CNTR_ISOLATE_WEST_MASK           XAIE4GBL_CORE_MODULE_TILE_CONTROL_ISOLATE_FROM_WEST_MASK_PRIVILEGED
#define XAIE_CORE_MOD_TILE_CNTR_ISOLATE_SOUTH_LSB           XAIE4GBL_CORE_MODULE_TILE_CONTROL_ISOLATE_FROM_SOUTH_LSB_PRIVILEGED
#define XAIE_CORE_MOD_TILE_CNTR_ISOLATE_SOUTH_MASK          XAIE4GBL_CORE_MODULE_TILE_CONTROL_ISOLATE_FROM_SOUTH_MASK_PRIVILEGED

#define XAIE_CORE_MOD_MEM_CNTR_REGOFF                       XAIE4GBL_CORE_MODULE_MEMORY_CONTROL_PRIVILEGED
#define XAIE_CORE_MOD_MEM_CNTR_ZEROISATION_LSB              XAIE4GBL_CORE_MODULE_MEMORY_CONTROL_MEMORY_ZEROISATION_LSB_PRIVILEGED
#define XAIE_CORE_MOD_MEM_CNTR_ZEROISATION_MASK             XAIE4GBL_CORE_MODULE_MEMORY_CONTROL_MEMORY_ZEROISATION_MASK_PRIVILEGED

#define XAIE_MEM_MOD_MEM_CNTR_REGOFF                        XAIE4GBL_MEMORY_MODULE_MEMORY_CONTROL_PRIVILEGED
#define XAIE_MEM_MOD_MEM_CNTR_ZEROISATION_LSB               XAIE4GBL_MEMORY_MODULE_MEMORY_CONTROL_MEMORY_ZEROISATION_LSB_PRIVILEGED
#define XAIE_MEM_MOD_MEM_CNTR_ZEROISATION_MASK              XAIE4GBL_MEMORY_MODULE_MEMORY_CONTROL_MEMORY_ZEROISATION_MASK_PRIVILEGED

#define XAIE_MEM_TILE_MOD_TILE_CNTR_REGOFF                  XAIE4GBL_MEM_TILE_MODULE_TILE_CONTROL_PRIVILEGED
#define XAIE_MEM_TILE_MOD_TILE_CNTR_ISOLATE_EAST_LSB        XAIE4GBL_MEM_TILE_MODULE_TILE_CONTROL_ISOLATE_FROM_EAST_LSB_PRIVILEGED
#define XAIE_MEM_TILE_MOD_TILE_CNTR_ISOLATE_EAST_MASK       XAIE4GBL_MEM_TILE_MODULE_TILE_CONTROL_ISOLATE_FROM_EAST_MASK_PRIVILEGED
#define XAIE_MEM_TILE_MOD_TILE_CNTR_ISOLATE_NORTH_LSB       XAIE4GBL_MEM_TILE_MODULE_TILE_CONTROL_ISOLATE_FROM_NORTH_LSB_PRIVILEGED
#define XAIE_MEM_TILE_MOD_TILE_CNTR_ISOLATE_NORTH_MASK      XAIE4GBL_MEM_TILE_MODULE_TILE_CONTROL_ISOLATE_FROM_NORTH_MASK_PRIVILEGED
#define XAIE_MEM_TILE_MOD_TILE_CNTR_ISOLATE_WEST_LSB        XAIE4GBL_MEM_TILE_MODULE_TILE_CONTROL_ISOLATE_FROM_WEST_LSB_PRIVILEGED
#define XAIE_MEM_TILE_MOD_TILE_CNTR_ISOLATE_WEST_MASK       XAIE4GBL_MEM_TILE_MODULE_TILE_CONTROL_ISOLATE_FROM_WEST_MASK_PRIVILEGED
#define XAIE_MEM_TILE_MOD_TILE_CNTR_ISOLATE_SOUTH_LSB       XAIE4GBL_MEM_TILE_MODULE_TILE_CONTROL_ISOLATE_FROM_SOUTH_LSB_PRIVILEGED
#define XAIE_MEM_TILE_MOD_TILE_CNTR_ISOLATE_SOUTH_MASK      XAIE4GBL_MEM_TILE_MODULE_TILE_CONTROL_ISOLATE_FROM_SOUTH_MASK_PRIVILEGED

#define XAIE_MEM_TILE_DUAL_APP_MODE                         XAIE4GBL_MEM_TILE_MODULE_DUAL_APP_MODE_PRIVILEGED
#define XAIE_MEM_TILE_DUAL_APP_MODE_LSB                     XAIE4GBL_MEM_TILE_MODULE_DUAL_APP_MODE_DUAL_APP_MODE_LSB_PRIVILEGED
#define XAIE_MEM_TILE_DUAL_APP_MODE_MASK                    XAIE4GBL_MEM_TILE_MODULE_DUAL_APP_MODE_DUAL_APP_MODE_MASK_PRIVILEGED

#define XAIE_MEM_TILE_L2_SPLIT_CONTROL                      XAIE4GBL_MEM_TILE_MODULE_L2_SPLIT_PRIVILEGED
#define XAIE_MEM_TILE_L2_SPLIT_CONTROL_LSB                  XAIE4GBL_MEM_TILE_MODULE_L2_SPLIT_L2_SPLIT_LSB_PRIVILEGED
#define XAIE_MEM_TILE_L2_SPLIT_CONTROL_MASK                 XAIE4GBL_MEM_TILE_MODULE_L2_SPLIT_MASK_PRIVILEGED

#define XAIE_MEM_TILE_MOD_MEM_CNTR_REGOFF                   XAIE4GBL_MEM_TILE_MODULE_MEMORY_ZEROIZATION_A_PRIVILEGED
#define XAIE_MEM_TILE_MOD_MEM_CNTR_REGOFF_B                 XAIE4GBL_MEM_TILE_MODULE_MEMORY_ZEROIZATION_B_PRIVILEGED
#define XAIE_MEM_TILE_MEM_CNTR_ZEROISATION_LSB              XAIE4GBL_MEM_TILE_MODULE_MEMORY_ZEROIZATION_A_MEMORY_ZEROISATION_LSB_PRIVILEGED
#define XAIE_MEM_TILE_MEM_CNTR_ZEROISATION_MASK             XAIE4GBL_MEM_TILE_MODULE_MEMORY_ZEROIZATION_A_MEMORY_ZEROISATION_MASK_PRIVILEGED

/* Tile control isolation bits are the same across tiles */
#define XAIE_TILE_CNTR_ISOLATE_EAST_MASK                    XAIE_CORE_MOD_TILE_CNTR_ISOLATE_EAST_MASK
#define XAIE_TILE_CNTR_ISOLATE_WEST_MASK                    XAIE_CORE_MOD_TILE_CNTR_ISOLATE_WEST_MASK

/* DMA Status Registers */
#define XAIE_TILE_DMA_S2MM_CHANNEL_STATUS_REGOFF            XAIE4GBL_MEMORY_MODULE_DMA_S2MM_0_STATUS
#define XAIE_TILE_DMA_S2MM_CHANNEL_VALID_BITS_MASK          XAIE4GBL_MEMORY_MODULE_DMA_S2MM_0_STATUS_MASK
#define XAIE_TILE_DMA_S2MM_CHANNEL_STATUS_MASK              XAIE4GBL_MEMORY_MODULE_DMA_S2MM_0_STATUS_STATUS_MASK
#define XAIE_TILE_DMA_S2MM_CHANNEL_RUNNING_MASK             XAIE4GBL_MEMORY_MODULE_DMA_S2MM_0_STATUS_CHANNEL_RUNNING_MASK
#define XAIE_TILE_DMA_S2MM_CHANNEL_STATUS_IDX               0x4

#define XAIE_TILE_DMA_MM2S_CHANNEL_STATUS_REGOFF            XAIE4GBL_MEMORY_MODULE_DMA_MM2S_0_STATUS
#define XAIE_TILE_DMA_MM2S_CHANNEL_VALID_BITS_MASK          XAIE4GBL_MEMORY_MODULE_DMA_MM2S_0_STATUS_MASK
#define XAIE_TILE_DMA_MM2S_CHANNEL_STATUS_MASK              XAIE4GBL_MEMORY_MODULE_DMA_MM2S_0_STATUS_STATUS_MASK
#define XAIE_TILE_DMA_MM2S_CHANNEL_RUNNING_MASK             XAIE4GBL_MEMORY_MODULE_DMA_MM2S_0_STATUS_CHANNEL_RUNNING_MASK
#define XAIE_TILE_DMA_MM2S_CHANNEL_STATUS_IDX               0x4

#define XAIE_MEM_TILE_DMA_S2MM_CHANNEL_STATUS_REGOFF        XAIE4GBL_MEM_TILE_MODULE_DMA_S2MM_0_STATUS
#define XAIE_MEM_TILE_DMA_S2MM_CHANNEL_VALID_BITS_MASK      XAIE4GBL_MEM_TILE_MODULE_DMA_S2MM_0_STATUS_MASK
#define XAIE_MEM_TILE_DMA_S2MM_CHANNEL_STATUS_MASK          XAIE4GBL_MEM_TILE_MODULE_DMA_S2MM_0_STATUS_STATUS_MASK
#define XAIE_MEM_TILE_DMA_S2MM_CHANNEL_RUNNING_MASK         XAIE4GBL_MEM_TILE_MODULE_DMA_S2MM_0_STATUS_CHANNEL_RUNNING_MASK
#define XAIE_MEM_TILE_DMA_S2MM_CHANNEL_STATUS_IDX           0x4

#define XAIE_MEM_TILE_DMA_MM2S_CHANNEL_STATUS_REGOFF        XAIE4GBL_MEM_TILE_MODULE_DMA_MM2S_0_STATUS
#define XAIE_MEM_TILE_DMA_MM2S_CHANNEL_VALID_BITS_MASK      XAIE4GBL_MEM_TILE_MODULE_DMA_MM2S_0_STATUS_MASK
#define XAIE_MEM_TILE_DMA_MM2S_CHANNEL_STATUS_MASK          XAIE4GBL_MEM_TILE_MODULE_DMA_MM2S_0_STATUS_STATUS_MASK
#define XAIE_MEM_TILE_DMA_MM2S_CHANNEL_RUNNING_MASK         XAIE4GBL_MEM_TILE_MODULE_DMA_MM2S_0_STATUS_CHANNEL_RUNNING_MASK
#define XAIE_MEM_TILE_DMA_MM2S_CHANNEL_STATUS_IDX           0x4

#define XAIE_SHIM_DMA_S2MM_CHANNEL_STATUS_REGOFF            XAIE4GBL_NOC_MODULE_DMA_S2MM_0_STATUS
#define XAIE_SHIM_DMA_S2MM_CHANNEL_VALID_BITS_MASK          XAIE4GBL_NOC_MODULE_DMA_S2MM_0_STATUS_MASK
#define XAIE_SHIM_DMA_S2MM_CHANNEL_STATUS_MASK              XAIE4GBL_NOC_MODULE_DMA_S2MM_0_STATUS_STATUS_MASK
#define XAIE_SHIM_DMA_S2MM_CHANNEL_RUNNING_MASK             XAIE4GBL_NOC_MODULE_DMA_S2MM_0_STATUS_CHANNEL_RUNNING_MASK
#define XAIE_SHIM_DMA_S2MM_CHANNEL_STATUS_IDX               0x4

#define XAIE_SHIM_DMA_MM2S_CHANNEL_STATUS_REGOFF            XAIE4GBL_NOC_MODULE_DMA_MM2S_0_STATUS
#define XAIE_SHIM_DMA_MM2S_CHANNEL_VALID_BITS_MASK          XAIE4GBL_NOC_MODULE_DMA_MM2S_0_STATUS_MASK
#define XAIE_SHIM_DMA_MM2S_CHANNEL_STATUS_MASK              XAIE4GBL_NOC_MODULE_DMA_MM2S_0_STATUS_STATUS_MASK
#define XAIE_SHIM_DMA_MM2S_CHANNEL_RUNNING_MASK             XAIE4GBL_NOC_MODULE_DMA_MM2S_0_STATUS_CHANNEL_RUNNING_MASK
#define XAIE_SHIM_DMA_MM2S_CHANNEL_STATUS_IDX               0x4

/* Module reset control registers for AIE Core tile , MEM tile and SHIM tile is replaced by
 * Application reset
*/

#define XAIE_PL_MODULE_SPARE_REG                            XAIE4GBL_PL_MODULE_SPARE_REG_PRIVILEGED_PRIVILEGED

/* AIE Core Vector Registers */
#define XAIE_AIE_TILE_CORE_AMLL0_PART1_REGOFF               XAIE4GBL_CORE_INTERNAL_MODULE_CORE_BMLL0_PART1
#define XAIE_AIE_TILE_CORE_AMLL0_PART1_SIZE                 0x480

#define XAIE_AIE_TILE_CORE_WL0_PART1_REGOFF                 XAIE4GBL_CORE_INTERNAL_MODULE_CORE_X1_PART1
#define XAIE_AIE_TILE_CORE_WL0_PART1_SIZE                   0x300

/* Register information not present */
/*#define XAIE_AIE_TILE_CORE_R0_REGOFF                      XAIEMLGBL_CORE_MODULE_CORE_R0
#define XAIE_AIE_TILE_CORE_R0_COUNT                         32
#define XAIE_AIE_TILE_CORE_R0_STEP_SIZE                     0x10
#define XAIE_AIE_TILE_CORE_R0_SIZE                          0x200
*/

#define XAIE_MEM_TILE_LOCK_VALUE_REGOFF                     XAIE4GBL_MEM_TILE_MODULE_LOCK0_VALUE
#define XAIE_MEM_TILE_LOCK_VALUE_MASK                       XAIE4GBL_MEM_TILE_MODULE_LOCK0_VALUE_MASK
#define XAIE_MEM_TILE_LOCK_VALUE_IDX                        0x10

#define XAIE_AIE_TILE_CORE_STATUS_REGOFF                    XAIE4GBL_CORE_MODULE_CORE_STATUS
#define XAIE_AIE_TILE_CORE_STATUS_MASK                      XAIE4GBL_CORE_MODULE_CORE_STATUS_MASK

#define XAIE_AIE_TILE_CORE_PC_REGOFF                        XAIE4GBL_CORE_INTERNAL_MODULE_CORE_PC
#define XAIE_AIE_TILE_CORE_PC_MASK                          XAIE4GBL_CORE_INTERNAL_MODULE_CORE_PC_MASK

#define XAIE_AIE_TILE_CORE_SP_REGOFF                        XAIE4GBL_CORE_INTERNAL_MODULE_CORE_SP
#define XAIE_AIE_TILE_CORE_SP_MASK                          XAIE4GBL_CORE_INTERNAL_MODULE_CORE_SP_MASK

#define XAIE_AIE_TILE_CORE_LC_REGOFF                        XAIE4GBL_CORE_INTERNAL_MODULE_CORE_LC
#define XAIE_AIE_TILE_CORE_LC_MASK                          XAIE4GBL_CORE_INTERNAL_MODULE_CORE_LC_MASK

#define XAIE_AIE_TILE_CORE_LR_REGOFF                        XAIE4GBL_CORE_INTERNAL_MODULE_CORE_LR
#define XAIE_AIE_TILE_CORE_LR_MASK                          XAIE4GBL_CORE_INTERNAL_MODULE_CORE_LR_MASK

#define XAIE_AIE_TILE_LOCK_VALUE_REGOFF                     XAIE4GBL_MEMORY_MODULE_LOCK0_VALUE
#define XAIE_AIE_TILE_LOCK_VALUE_MASK                       XAIE4GBL_MEMORY_MODULE_LOCK0_VALUE_MASK
#define XAIE_AIE_TILE_LOCK_VALUE_IDX                        0x10

#define XAIE_SHIM_TILE_LOCK_VALUE_REGOFF                    XAIE4GBL_NOC_MODULE_LOCK0_VALUE
#define XAIE_SHIM_TILE_LOCK_VALUE_MASK                      XAIE4GBL_NOC_MODULE_LOCK0_VALUE_MASK
#define XAIE_SHIM_TILE_LOCK_VALUE_IDX                       0x10

#define XAIE_SHIM_TILE_EVENT_STATUS_REGOFF                  XAIE4GBL_PL_MODULE_EVENT_STATUS_A_0
#define XAIE_SHIM_TILE_EVENT_STATUS_MASK                    XAIE4GBL_PL_MODULE_EVENT_STATUS_A_0_MASK
#define XAIE_SHIM_TILE_EVENT_STATUS_IDX                     0x04

#define XAIE_MEM_TILE_EVENT_STATUS_REGOFF                   XAIE4GBL_MEM_TILE_MODULE_EVENT_STATUS_A_0
#define XAIE_MEM_TILE_EVENT_STATUS_MASK                     XAIE4GBL_MEM_TILE_MODULE_EVENT_STATUS_A_0_MASK
#define XAIE_MEM_TILE_EVENT_STATUS_IDX                      0x04

#define XAIE_AIE_TILE_CORE_MOD_EVENT_STATUS_REGOFF          XAIE4GBL_CORE_MODULE_EVENT_STATUS0
#define XAIE_AIE_TILE_CORE_MOD_EVENT_STATUS_MASK            XAIE4GBL_CORE_MODULE_EVENT_STATUS0_MASK
#define XAIE_AIE_TILE_CORE_MOD_EVENT_STATUS_IDX             0x04

#define XAIE_SHIM_TILE_MOD_CLOCK_CONTROL_0_REGOFF           XAIE4GBL_PL_MODULE_MODULE_CLOCK_CONTROL_0_PRIVILEGED
#define XAIE_SHIM_TILE_MOD_CLOCK_CONTROL_0_MASK             XAIE4GBL_PL_MODULE_MODULE_CLOCK_CONTROL_0_MASK_PRIVILEGED

#define XAIE_SHIM_TILE_MOD_CLOCK_CONTROL_0_CTE_CLOCK_ENABLE_LSB             XAIE4GBL_PL_MODULE_MODULE_CLOCK_CONTROL_0_CTE_CLOCK_ENABLE_LSB_PRIVILEGED
#define XAIE_SHIM_TILE_MOD_CLOCK_CONTROL_0_CTE_CLOCK_ENABLE_MASK            XAIE4GBL_PL_MODULE_MODULE_CLOCK_CONTROL_0_CTE_CLOCK_ENABLE_MASK_PRIVILEGED
#define XAIE_SHIM_TILE_MOD_CLOCK_CONTROL_0_PL_INTERFACE_CLOCK_ENABLE_LSB    XAIE4GBL_PL_MODULE_MODULE_CLOCK_CONTROL_0_PL_INTERFACE_CLOCK_ENABLE_LSB_PRIVILEGED
#define XAIE_SHIM_TILE_MOD_CLOCK_CONTROL_0_PL_INTERFACE_CLOCK_ENABLE_MASK   XAIE4GBL_PL_MODULE_MODULE_CLOCK_CONTROL_0_PL_INTERFACE_CLOCK_ENABLE_MASK_PRIVILEGED

#define XAIE_SHIM_TILE_MOD_CLOCK_CONTROL_1_REGOFF                       XAIE4GBL_PL_MODULE_MODULE_CLOCK_CONTROL_1_PRIVILEGED
#define XAIE_SHIM_TILE_MOD_CLOCK_CONTROL_1_MASK                         XAIE4GBL_PL_MODULE_MODULE_CLOCK_CONTROL_1_MASK_PRIVILEGED
#define XAIE_SHIM_TILE_NOC_MOD_CLOCK_CONTROL_1_CLOCK_ENABLE_LSB			XAIE4GBL_PL_MODULE_MODULE_CLOCK_CONTROL_1_NOC_MODULE_CLOCK_ENABLE_LSB_PRIVILEGED
#define XAIE_SHIM_TILE_NOC_MOD_CLOCK_CONTROL_1_CLOCK_ENABLE_MASK		XAIE4GBL_PL_MODULE_MODULE_CLOCK_CONTROL_1_NOC_MODULE_CLOCK_ENABLE_MASK_PRIVILEGED

#define XAIE_UC_MODULE_MEMORY_PRIVILEGED								XAIE4GBL_PL_MODULE_MEMORY_PRIVILEGED_PRIVILEGED
#define XAIE_UC_MODULE_MEMORY_PRIVILEGED_MEMORY_PRIVILEGED_LSB			XAIE4GBL_PL_MODULE_MEMORY_PRIVILEGED_MEMORY_PRIVILEGED_LSB_PRIVILEGED
#define XAIEGBL_UC_MODULE_MEMORY_PRIVILEGED_MEMORY_PRIVILEGED_MASK		XAIE4GBL_PL_MODULE_MEMORY_PRIVILEGED_MEMORY_PRIVILEGED_MASK_PRIVILEGED

/************************** Variable Definitions *****************************/
/************************** Function Prototypes  *****************************/
#define XAIE_CORE_PROGRAM_MEMORY                    XAIE4GBL_CORE_MODULE_PROGRAM_MEMORY
#define XAIE_CORE_PROGRAM_MEMORY_SIZE               32 * 1024
#define XAIE_CORE_MEMORY_MODULE_DATAMEMORY          XAIE4GBL_MEMORY_MODULE_DATAMEMORY
#define XAIE_CORE_DATA_MEMORY_SIZE                  128 * 1024
#define XAIE_MEM_TILE_MEMORY_MODULE_DATAMEMORY      XAIE4GBL_MEM_TILE_MODULE_DATAMEMORY
#define XAIE_MEM_TILE_MEMORY_SIZE                   3 * 1024 * 1024
#define XAIE_UC_PROGRAM_MEMORY                      XAIE4GBL_UC_MODULE_CORE_PROGRAM_MEMORY
#define XAIE_UC_PROGRAM_MEMORY_SIZE                 32 * 1024
#define XAIE_UC_PRIVATE_DATA_MEMORY                 XAIE4GBL_UC_MODULE_CORE_PRIVATE_DATA_MEMORY
#define XAIE_UC_PRIVATE_DATA_MEMORY_SIZE            16 * 1024
#define XAIE_UC_SHARED_DATA_MEMORY                  XAIE4GBL_UC_MODULE_MODULE_DATA_MEMORY
#define XAIE_UC_SHARED_DATA_MEMORY_SIZE             32 * 1024
#endif /* XAIE_LITE_REGDEF_AIE4_H_ */
